node {
	stage('获取更新'){
		echo '开始获取提交源码'
	}
}

node {
	stage('检查代码规范'){
		echo '开始检查代码规范'
	}
}

node {
	stage('自动化测试'){
		sh "pwd"
		echo 'mvn test'
	}
}

node {
	stage('是否通过？') {
		input 'Ready to go?'
		sh "curl www.baidu.com"
	}
	
}